#!/bin/bash
#cd /home/shashank/Downloads/676_final_version/Multi2sim/
#sudo make install
M2S='m2s --x86-sim detailed --x86-config /home/gaurav/Desktop/Multi2sim-Semifinal/samples/x86/x86-acmp-2b6s-config --x86-report out_parsec_m4 --max-time 500'
PARSEC=/home/gaurav/Desktop/m2s-benchmarks-parsec-2.1
NThreads=32
OUTFILE=m2s_parsec_m4
BATCHSIZE=4 #number of things that run at a time

BATCHSIZE=$[$BATCHSIZE-1]
killall m2s 

#need these two environment variables for some benchmarks 
OMP_NUM_THREADS=$NThreads
IM_CONCURRENCY=$NThreads 


echo 'Running fluidanimate'
cd $PARSEC/fluidanimate  && $M2S ./fluidanimate  $NThreads 5 in_100K.fluid out.fluid &>$OUTFILE && echo 'fluidanimate finished'&

RUNNING_M2S=`ps | grep m2s | wc -l`
while [ $RUNNING_M2S -gt $BATCHSIZE ]; do sleep 1; RUNNING_M2S=`ps | grep m2s | wc -l`; done
echo 'Running Canneal'
cd $PARSEC/canneal  && $M2S ./canneal $NThreads 15000 2000 200000.nets 64 &>$OUTFILE && echo 'Canneal finished'&

RUNNING_M2S=`ps | grep m2s | wc -l`
while [ $RUNNING_M2S -gt $BATCHSIZE ]; do sleep 1; RUNNING_M2S=`ps | grep m2s | wc -l`; done
echo 'Running dedup'
cd $PARSEC/dedup && $M2S ./dedup -c -p -f -t $NThreads -i media.dat -o output.dat.dd &> $OUTFILE && echo 'Dedup finished' &


RUNNING_M2S=`ps | grep m2s | wc -l`
while [ $RUNNING_M2S -gt $BATCHSIZE ]; do sleep 1; RUNNING_M2S=`ps | grep m2s | wc -l`; done
echo 'Running facesim'
cd $PARSEC/facesim  && $M2S ./facesim -timing -threads  $NThreads &>$OUTFILE &&echo 'facesim finished'& 

RUNNING_M2S=`ps | grep m2s | wc -l`
while [ $RUNNING_M2S -gt $BATCHSIZE ]; do sleep 1; RUNNING_M2S=`ps | grep m2s | wc -l`; done
echo 'Running streamcluster'
cd $PARSEC/streamcluster && $M2S ./streamcluster 10 20 64 8192 8192 1000 none output.txt $NThreads &> $OUTFILE && echo 'streamcluster finished'  &

RUNNING_M2S=`ps | grep m2s | wc -l`
while [ $RUNNING_M2S -gt $BATCHSIZE ]; do sleep 1; RUNNING_M2S=`ps | grep m2s | wc -l`; done
echo 'Running swaptions'
cd $PARSEC/swaptions && $M2S ./swaptions -ns 32 -sm 10000 -nt $NThreads  &>$OUTFILE && echo 'swaptions finished'&

RUNNING_M2S=`ps | grep m2s | wc -l`
while [ $RUNNING_M2S -gt $BATCHSIZE ]; do sleep 1; RUNNING_M2S=`ps | grep m2s | wc -l`; done
echo 'Running blackscholes'
cd $PARSEC/blackscholes && $M2S ./blackscholes $NThreads in_16K.txt prices.txt &> $OUTFILE && echo 'blacksholes finished'&

RUNNING_M2S=`ps | grep m2s | wc -l`
while [ $RUNNING_M2S -gt $BATCHSIZE ]; do sleep 1; RUNNING_M2S=`ps | grep m2s | wc -l`; done
echo 'Running bodytrack'
cd $PARSEC/bodytrack  && $M2S ./bodytrack sequenceB_2 4 2 2000 5 0  $NThreads &>$OUTFILE && echo 'bodytrack finished'&


RUNNING_M2S=`ps | grep m2s | wc -l`
while [ $RUNNING_M2S -gt $BATCHSIZE ]; do sleep 1; RUNNING_M2S=`ps | grep m2s | wc -l`; done
echo 'Running raytrace'
cd $PARSEC/raytrace && $M2S ./rtview happy_buddha.obj -nodisplay -automove -nthreads  $NThreads -frames 3 -res 960 540 &>$OUTFILE && echo 'raytrace finished' &

RUNNING_M2S=`ps | grep m2s | wc -l`
while [ $RUNNING_M2S -gt $BATCHSIZE ]; do sleep 1; RUNNING_M2S=`ps | grep m2s | wc -l`; done
echo 'Running x264'
cd $PARSEC/x264 && $M2S ./x264 --quiet --qp 20 --partitions b8x8,i4x4 --ref 5 --direct auto --b-pyramid --weightb --mixed-refs --no-fast-pskip --me umh --subme 7 --analyse b8x8,i4x4 --threads $NThreads -o eledream.264 eledream_640x360_32.y4m &> $OUTFILE && echo 'x264 finished' & 

RUNNING_M2S=`ps | grep m2s | wc -l`
while [ $RUNNING_M2S -gt $BATCHSIZE ]; do sleep 1; RUNNING_M2S=`ps | grep m2s | wc -l`; done
echo 'Running ferret'
cd $PARSEC/ferret && $M2S ./ferret corel lsh queries 10 20 $NThreads output.txt &>$OUTFILE && echo 'x264 finished' &

RUNNING_M2S=`ps | grep m2s | wc -l`
while [ $RUNNING_M2S -gt $BATCHSIZE ]; do sleep 1; RUNNING_M2S=`ps | grep m2s | wc -l`; done
echo 'Running vips'
cd $PARSEC/vips && $M2S ./vips im_benchmark vulture_2336x2336.v output.v &>$OUTFILE && echo 'vips finished' & 
