#! /bin/bash
M2S='m2s --x86-sim detailed --x86-config /home/gaurav/Desktop/Multi2sim-Semifinal/samples/x86/x86-acmp-2b6s-config --x86-report out_x86_report --max-time 500'
SPLASH=/home/gaurav/Desktop/m2s-benchmarks-splash2
NThreads=32
OUTFILE=m2s_splash
BATCHSIZE=4 #number of things that run at a time

BATCHSIZE=$[$BATCHSIZE-1]
killall m2s 


echo 'Running Barnes'
cd $SPLASH/barnes && $M2S ./barnes.i386 $NThreads < input  &> $OUTFILE  && echo 'barnes finished' &

RUNNING_M2S=`ps | grep m2s | wc -l`
while [ $RUNNING_M2S -gt $BATCHSIZE ]; do sleep 1; RUNNING_M2S=`ps | grep m2s | wc -l`; done
echo 'Running fft'
cd $SPLASH/fft  && $M2S ./fft.i386 -m18 -p$NThreads -n65536 -l4 &>$OUTFILE && echo 'fft finished' &

RUNNING_M2S=`ps | grep m2s | wc -l`
while [ $RUNNING_M2S -gt $BATCHSIZE ]; do sleep 1; RUNNING_M2S=`ps | grep m2s | wc -l`; done
echo 'Running lu'
cd $SPLASH/lu  && $M2S ./lu.i386 -p $NThreads -n512 -b16   &>$OUTFILE  && echo 'lu finished' &

RUNNING_M2S=`ps | grep m2s | wc -l`
while [ $RUNNING_M2S -gt $BATCHSIZE ]; do sleep 1; RUNNING_M2S=`ps | grep m2s | wc -l`; done
echo 'Running radiosity'
cd $SPLASH/radiosity  && $M2S ./radiosity.i386 -batch -p $NThreads -en 0.5 &>$OUTFILE && echo 'radiosity finished' &

RUNNING_M2S=`ps | grep m2s | wc -l`
while [ $RUNNING_M2S -gt $BATCHSIZE ]; do sleep 1; RUNNING_M2S=`ps | grep m2s | wc -l`; done
echo 'Running raytrace'
cd $SPLASH/raytrace  && $M2S ./raytrace.i386  -p$NThreads  balls4.env &>$OUTFILE && echo 'raytrace finished' &

RUNNING_M2S=`ps | grep m2s | wc -l`
while [ $RUNNING_M2S -gt $BATCHSIZE ]; do sleep 1; RUNNING_M2S=`ps | grep m2s | wc -l`; done
echo 'Running water-spatial'
cd $SPLASH/water-spatial && $M2S ./water-spatial.i386  $NThreads -frames 3  &>$OUTFILE && echo 'water-spatial finished' &

RUNNING_M2S=`ps | grep m2s | wc -l`
while [ $RUNNING_M2S -gt $BATCHSIZE ]; do sleep 1; RUNNING_M2S=`ps | grep m2s | wc -l`; done
echo 'Running cholesky'
cd $SPLASH/cholesky && $M2S ./cholesky.i386 -p$NThreads  &>$OUTFILE && echo 'cholesky finished' &

RUNNING_M2S=`ps | grep m2s | wc -l`
while [ $RUNNING_M2S -gt $BATCHSIZE ]; do sleep 1; RUNNING_M2S=`ps | grep m2s | wc -l`; done
echo 'Running fmm'
cd $SPLASH/fmm && $M2S ./fmm.i386 $NThreads <input &> $OUTFILE   && echo 'fmm finished' &

RUNNING_M2S=`ps | grep m2s | wc -l`
while [ $RUNNING_M2S -gt $BATCHSIZE ]; do sleep 1; RUNNING_M2S=`ps | grep m2s | wc -l`; done
echo 'Running ocean'
cd $SPLASH/ocean && $M2S ./ocean.i386  -n130  -p $NThreads -e1e-07 -r20000 -t28800 &> $OUTFILE  && echo 'ocean finished' &

RUNNING_M2S=`ps | grep m2s | wc -l`
while [ $RUNNING_M2S -gt $BATCHSIZE ]; do sleep 1; RUNNING_M2S=`ps | grep m2s | wc -l`; done
echo 'Running radix'
cd $SPLASH/radix && $M2S ./radix.i386 -p $NThreads -r4096 -n262144 -m524288 &> $OUTFILE && echo 'radix finished' &

RUNNING_M2S=`ps | grep m2s | wc -l`
while [ $RUNNING_M2S -gt $BATCHSIZE ]; do sleep 1; RUNNING_M2S=`ps | grep m2s | wc -l`; done
echo 'Running water-nsquared'
cd $SPLASH/water-nsquared && $M2S ./streamcluster.i386 ./water-nsquared.i386 $NThreads <input  &> $OUTFILE  && echo 'water-nsquared finished' &
